### PR TITLE
Change some Russian strings in setup file back to English (how it should be)

### PR DESCRIPTION
**Pull request by abalabokhin**
Some string in setup file were fixed for Russian translation (thanks to yota13 from arcanecoast.ru). However, even after the fix the Russian language doesn't work properly for EE version. There are some line in wrong encoding (looks like all the lines but setup file, shall they be reloaded after encoding?). E.g. lines @106945 and @106946 has proper encoding, while all the other lines are not:

```
@106945 = ~Магический Снаряд
Уровень: 1
Школа: Вызывание
Дистанция: Большая
Продолжительность: Мгновенная
Время произнесения заклинания: 1
Область действия: 1 существо
Спасительный бросок: Нет

Использование заклятья Магического Снаряда, одного из наиболее популярных заклятий первого уровня, создает до пяти стрел волшебной энергии, которые слетают с кончиков пальцев мага и без промаха попадают в цель, которой может быть любое существо. Каждая стрела причиняет 1d4+1 пунктов повреждений. На каждые два дополнительные уровня опыта маг получает дополнительную стрелу - два на 3-ем уровне, три на 5-ом уровне, четыре на 7-ом уровне, и максимально пять стрел на 9-ом уровне.~
@106946 = ~Планарная Сфера~
@106947 = ~Àࠠࠠõ!!!!!!!! Á壨򥡡!~
@106948 = ~ײ볷諮񼿾
@106949 = ~ĥ쮭û! ʰ󣮬 䥬!~
@106950 = ~ĥ쮭û?!~
@106951 = ~» ÷򮬠ⱥ 㫳õ西 ߠÎО ą̎͛! Àࠠࠡ ѯౠ鱿 겮 쮦岡~
@106952 = ~Àõ, ý򮠲મ堧ଥ÷ಥ뼭쥱򮠤뿠�ø 㰠ᥦம. ࠲û 겮?!~
@106953 = ~ߠ- 竮頀𵨬࣡ À ꮣû 幥 䠫蠢񲰥򨲼 ⠭审û÷੭젣跥񪮩 񴥰忾
@106954 = ~ݲࠑ�� ﰨ�륦負쭥. À ⻠÷򮠲󲠤嫠岥?~
@106955 = ~ì... 跭ꠧ୮. ͮ �񬮲𿠭࠽򮬠򠪨õ ꠪ 򻬠컠󦥠󡨢૨.~
@106956 = ~ë󯶻! » 䳬ॲ嬠÷򮠱쮦岥 ﮡ夨򼠬孿 ⠬ 񮡱򢥭� 䮬忡 Ȥ讲û! ʰ岨� ̮ÿ 젣迠󭨷򮦨򠢠񡠓차򥬠ﰮ꫿򻥠⻱ꮷꨡ ʮ 쭥, 쮨 󷥭誨!  ø ̠񲥰 箢岠⠱!~
@106957 = ~ײ򮿾
@106958 = ~ݲࠑ�� ᮫üø堭堲⮿! ̻ ⮧ü쥬 ⱥ, ÷򮠧൮򨬡 Ƞ컠�񮡨𠥬񿠱 򮡮頱÷負򼱿, 䠬 𥡿򠿾
@106959 = ~» ÷򮬠õ򥠯𨬥�ü �諨忾
@106960 = ~°嬿 󬥰岼, 젣. ՠ-õ஠ ÀҀʓ!~
@106961 = ~ʮ 쭥, 쮨 󷥭议.~
@106962 = ~ײம?~
@106963 = ~εõõ, ÿ 񲰠ø�ᮾ񼡠Ϯ쮣貥 쭥! Ϯ쮣貥 쭥! ѯ౨򥠬孿 쮣󷨵 ⮫ø塭誮⬠ꮲ堳ᨢྲ 젭�젰󪨡~
@106964 = ~*§䮵* Ġ, ý򮠡û뮠ﮦ૳頤থ 񬥸� �򠪠먿 ˠ䭮, �⠦� ʠ楲񿬠쭥 ﰨ䥲񿠫跭ౠ󡨲ü!~
@106965 = ~ű먠򻠱𠦠帼񿠲ઠ楬 ꠪ ﰥﮤॸü, ﰮ᫥젱 򮡮頳 � �᳤岡~
@106966 = ~̠㬠ý򮲠㮰ừ 񫨸ꮬ 䮫㮠砣𿧭孠򢮨젯𨱳򱲢襬! ̻ 󭨷򮦨젲塿 蠲⮾ 觢𠹥�þ 젣辡~
@106967 = ~Ġ 겮 ⻠򠪨忾
@106968 = ~Ӡ� � 謥�- 򮫼ꮠö嫼. ֥뼠󭨷򮦠򼠫þ᳾ 젣辠蠥堰ৢ𠹥�õ �貥륩, ÷򮡻  ᮫üø堭堬蠨㰠򼠱 ⥹ନ, ꮲõ �ﮭ謠þ򡾍
@106969 = ~ͮ ⥤ü 젣迠ﰨ�負򠪳þ 󾠯糡 Ϯ÷嬳 ⻠õ򥠥堳�򮦨򼿾
@106970 = ~ײ, 屫蠢û 蹨򥠬ࣨþ, 򮠯𨡻먠򳤠, 㤥 奠⠨硻򪥮 ϰ失򠭼򥠯尥䮠쭮頨 󬰨򥡾
@106971 = ~Ϯ뼧󮮮 ®笮歮, �쭮㨥 豯糾򠥥 ⠧뻵 ö嫿õ... ݲ㰮栥򠭠ø嬳 񳹥񲢮⠭辠蠭ล쳠쨰󮠌ࣨÿ 䮫歠 Ỳü 󭨷򮦥�~
@106972 = ~լ... ͮ �⠱ �岮 ÷尲ꨠ쭮㮠砷మ⠭� ⥹趮.. ݲ堬ࣨÿ. Ƞ⻠ﮫü糥򥱼 微 Р碥 ý򮠭堧�責 ÷򮠢û ⨭򻠭ఠ⭥ 񮠬� ⠲嵠楠ﰥ񲳯륭迵, ⠪𻵠쥭ÿ 譿岥?~
@106973 = ~Ү㤠 󠬥��ॲ񿠨�û᮰ଠ갮쥠꠪ 󡨲ü ⠱!~
@106974 = ~ì... � ﮫ࣠þ, 䠮 *ϰùॲ 㮰뮪 ̮뷠򼡠̻ 󦥠�본૨񼠲⮨õ 񫠤ꨵ 𥷥頖 �孭򢮩 㮫�嫥�ࣨ÷屪񨫮頨 쮦岠砱򠢨򼠬û񫨠ﳲ಼񿡠͠ø蠬ࣨ÷屪襠ଳ륲û ��� 򮫼ꮠ䫿 򮣮, ÷򮡻 觭跲򼠲嵬 겮 赠񮧤ૡ~
@106975 = ~ͳ ÷򮠦, 屫蠢û �򠨢ॲ堭࠱𠦥�... ͮ ⠣볡譥 䳸蠢û 楠ﮭ謠岥, ÷򮠦嫠岥 �?~
@106976 = ~Ү㤠 䥰豼, �򮦥񲢮! Ϯ񬮲𨬬 ÷򮠲⮥ 㫳ﮥ 樥 񬮦岠ﰮ򨢠쮥頬ࣨ衾
@106977 = ~Ǡ쮫÷謠ᮣ뼭誡 Ң樧�砪貱ÿ 礥񼡾
@106978 = ~Ѭ孥-孥-尲ü!~
@106979 = ~ͥ򬠿 򠪠�䳬ྡ Ң竮⮭� 젣迠�񯠱岠򥡿 �÷塾
@106980 = ~ë󯻩 젣! ͠ �嬠񷥲󠳦堤屿򪨠򠪨õ, ꠪ 򻡾
@106981 = ~ε, <PRO_SIRMAAM>! Ϯ餥첥 ự򰥥. °ࣨ Ⲯ𣫨񼠢 ϫୠ𭳾 Ѵ尳. ߠ�䳬ྫྷ ÷򮠬û 쮦嬠୮⨲ü 赮~
```

### CODE REVIEW

**Comment by 11jo** [comment]
Hello Paladin84,

Yes, you are right, I didn't see the error until I was working on another mod with a French translation, because the problem didn't appear in English.

I think adding Autotra on the Auto_tra line in tp2 corrects the issue.

Can you do tests with the Russian translation for EE and the original game?

Thanks for correcting the setup.tra.

**Comment by abalabokhin** [comment]
Unfortunately, I don't have the original game. 
For EE, it is much better now, but it is still has some lines in CP1251, particularly lines from ar0300.tra, ar0900.tra and AR0700.tra files. Probably, it is because of line `USING ~PlanarSphereMod/language/%s/ar0900.tra~` in tp2 file and similar lines.

**Comment by 11jo** [comment]
You are right again, I try to use a new function to manage Handle Charset but I don't "handle" it yet...

I hope this time will be the right one !


**Edit:** 

Not sure if it is good, it is possible that USING does not choose the right file...

**Comment by abalabokhin** [comment]
Works perfectly for me - everything has proper encoding. Thanks a lot!

**Comment by 11jo** [comment]
Ok, great !

Thank you for your help !

**Pull request merged**
